### ISSUE TITLE
Gallery Image Ordering isn't working

### ISSUE THREAD

**Issue by mpiontek** [projectestac/wordpress-theme-fukasawa#10]
Hey guys,

my wordpress is on current version. Now the ordering of the Gallery images in a post of the post type Gallery isn't working. The images in the slider are showing up in completely different order, than i dragged it in the edit window.
I tried to fix it in the functions, but i can't find a way to get the right order, which the author drags and drops the images.

Is that a known problem, and are there some tips, how to solve this problem?

Best regards - Martin

**Comment by slva** [comment]
Hi Martin,

We are not the official maintainers of the fukasawa theme, please visit the official plugin page (https://wordpress.org/themes/fukasawa/) and ask your questions there.
